{
    "openapi": "3.0.0",
    "info": {
        "description": "This is Personal Loan Quotes",
        "version": "1.0.0",
        "title": "Personal Loan Quotes",
        "contact": {
            "name": "Service Desk",
            "url": "https://www.bankofapis.com/support"
        },
        "license": {
            "name": "Commercial Licence",
            "url": "https://www.bankofapis.com/commercial-licence"
        }
    },
    "servers": [
        {
            "url": "https://api.natwest.com/"
        }
    ],
    "paths": {
        "/customer/v1/search": {
            "post": {
                "tags": [
                    "Personal Loan Quotes"
                ],
                "summary": "Identify a customer",
                "description": "Attempts to match a customer, given one or more attributes",
                "operationId": "identifyCustomer",
                "requestBody": {
                    "description": "Customer attributes to match on. Provide one or more",
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/CustomerMatchRequest"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/CustomerMatchResponse"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ErrorResponse"
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "405": {
                        "description": "Method Not Allowed"
                    },
                    "406": {
                        "description": "Not Acceptable"
                    },
                    "408": {
                        "description": "Request Timeout"
                    },
                    "415": {
                        "description": "Unsupported Media Type"
                    },
                    "422": {
                        "description": "Not matched",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ErrorResponse"
                                }
                            }
                        }
                    },
                    "429": {
                        "description": "Too Many Requests",
                        "headers": {
                            "Retry-After": {
                                "description": "Number in seconds to wait",
                                "schema": {
                                    "type": "integer"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ErrorResponse"
                                }
                            }
                        }
                    },
                    "502": {
                        "description": "Bad Gateway"
                    },
                    "503": {
                        "description": "Service Unavailable"
                    },
                    "504": {
                        "description": "Gateway Timeout"
                    }
                },
                "security": [
                    {
                        "clientCreds": [
                            "customer:search"
                        ]
                    }
                ]
            }
        },
        "/illustrations/v1/criteria/personal-loan": {
            "get": {
                "tags": [
                    "Personal Loan Quotes"
                ],
                "summary": "Retrieve criteria parameters for loan illustration",
                "description": "Provides parameters for lending illustrations - tailored to the customer if provided",
                "operationId": "getPersonalLoanCriteria",
                "parameters": [
                    {
                        "name": "customerId",
                        "description": "Optional customerId query string parameter to tailor options to a specific customer",
                        "in": "query",
                        "schema": {
                            "type": "string",
                            "format": "[A-F0-9]+"
                        },
                        "example": "ABC123FED"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Returns the parameters used for personal-loan lending illustrations",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/GetCriteriaPersonalLoansResponse"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ErrorResponse"
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "405": {
                        "description": "Method Not Allowed"
                    },
                    "406": {
                        "description": "Not Acceptable"
                    },
                    "415": {
                        "description": "Unsupported Media Type"
                    },
                    "422": {
                        "description": "Not matched",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ErrorResponse"
                                }
                            }
                        }
                    },
                    "429": {
                        "description": "Too Many Requests",
                        "headers": {
                            "Retry-After": {
                                "description": "Number in seconds to wait",
                                "schema": {
                                    "type": "integer"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ErrorResponse"
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "clientCreds": [
                            "illustrations:read"
                        ]
                    }
                ]
            }
        },
        "/illustrations/v1/quote/personal-loan": {
            "post": {
                "tags": [
                    "Personal Loan Quotes"
                ],
                "summary": "Retrieve loan illustration",
                "description": "Provides a personal-loan illustration - tailored to a customer if provided",
                "operationId": "createIllustration",
                "requestBody": {
                    "description": "Provide personal-loan parameters to create an illustration",
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/CreateIllustrationPersonalLoanRequest"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/CreateIllustrationPersonalLoanResponse"
                                },
                                "examples": {
                                    "accepted": {
                                        "value": {
                                            "decision": "ACCEPTED",
                                            "personalLoanIllustration": {
                                                "apr": 330,
                                                "interestRate": 340,
                                                "totalRepaymentInPence": 1034664,
                                                "totalInterestInPence": 34664,
                                                "repayment": {
                                                    "amountInPence": 43111,
                                                    "interval": "MONTHLY"
                                                }
                                            },
                                            "reasons": []
                                        }
                                    },
                                    "declined": {
                                        "value": {
                                            "decision": "DECLINED",
                                            "reasons": [
                                                {
                                                    "id": "DEC0010",
                                                    "code": "MINIMUM_AGE",
                                                    "text": "Customer too young"
                                                },
                                                {
                                                    "id": "DEC0200",
                                                    "code": "DECLINED",
                                                    "text": "Unable to offer loan"
                                                }
                                            ]
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ErrorResponse"
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "405": {
                        "description": "Method Not Allowed"
                    },
                    "406": {
                        "description": "Not Acceptable"
                    },
                    "415": {
                        "description": "Unsupported Media Type"
                    },
                    "422": {
                        "description": "Validation failure",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ErrorResponse"
                                }
                            }
                        }
                    },
                    "429": {
                        "description": "Too Many Requests",
                        "headers": {
                            "Retry-After": {
                                "description": "Number in seconds to wait",
                                "schema": {
                                    "type": "integer"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ErrorResponse"
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "clientCreds": [
                            "illustrations:create"
                        ]
                    }
                ]
            }
        }
    },
    "components": {
        "securitySchemes": {
            "clientCreds": {
                "type": "oauth2",
                "flows": {
                    "clientCredentials": {
                        "scopes": {
                            "illustrations:read": "Grants read access to Illustration APIs",
                            "illustrations:create": "Grants create access to Illustration APIs",
                            "customer:search": "Grants search access to Customer APIs"
                        },
                        "tokenUrl": "https://secure1t.natwest.com/as/token.oauth2"
                    }
                }
            }
        },
        "schemas": {
            "CustomerMatchRequest": {
                "type": "object",
                "properties": {
                    "email": {
                        "type": "string"
                    },
                    "phoneNumber": {
                        "type": "string"
                    }
                },
                "example": {
                    "email": "ron.savage@bankofapis.com",
                    "phoneNumber": "01122334455"
                }
            },
            "CustomerMatchResponse": {
                "type": "object",
                "properties": {
                    "customerId": {
                        "type": "string"
                    }
                },
                "required": [
                    "customerId"
                ],
                "example": {
                    "customerId": "ABC123FED"
                }
            },
            "GetCriteriaPersonalLoansResponse": {
                "type": "object",
                "properties": {
                    "purposes": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "id": {
                                    "type": "string",
                                    "enum": [
                                        "NV (New Vehicle)",
                                        "UV (Used Vehicle)",
                                        "HI (Home Improvements)",
                                        "HG (Household Goods)",
                                        "HO (Holiday)",
                                        "DC (Debt Consolidation)",
                                        "WE (Wedding)",
                                        "OP (Other Acceptable Purposes)"
                                    ]
                                },
                                "name": {
                                    "type": "string"
                                },
                                "suggested": {
                                    "type": "object",
                                    "properties": {
                                        "termInMonths": {
                                            "type": "array",
                                            "items": {
                                                "type": "integer",
                                                "format": "int32"
                                            }
                                        },
                                        "amountInPence": {
                                            "type": "array",
                                            "items": {
                                                "type": "integer",
                                                "format": "int32"
                                            }
                                        }
                                    },
                                    "required": [
                                        "termInMonths",
                                        "amountInPence"
                                    ]
                                },
                                "criteria": {
                                    "type": "array",
                                    "items": {
                                        "type": "object",
                                        "properties": {
                                            "termInMonths": {
                                                "$ref": "#/components/schemas/CriteriaValue"
                                            },
                                            "amountInPence": {
                                                "$ref": "#/components/schemas/CriteriaValue"
                                            }
                                        },
                                        "required": [
                                            "termInMonths",
                                            "amountInPence"
                                        ]
                                    }
                                }
                            },
                            "required": [
                                "id",
                                "name",
                                "criteria",
                                "suggested"
                            ]
                        }
                    }
                },
                "required": [
                    "purposes"
                ],
                "example": {
                    "purposes": [
                        {
                            "id": "HI",
                            "name": "Home Improvement",
                            "suggested": {
                                "termInMonths": [
                                    24,
                                    36,
                                    48,
                                    60,
                                    120
                                ],
                                "amountInPence": [
                                    200000,
                                    500000,
                                    100000,
                                    2500000
                                ]
                            },
                            "criteria": [
                                {
                                    "termInMonths": {
                                        "min": 24,
                                        "max": 60,
                                        "increment": 6
                                    },
                                    "amountInPence": {
                                        "min": 100000,
                                        "max": 745000,
                                        "increment": 5000
                                    }
                                },
                                {
                                    "termInMonths": {
                                        "min": 24,
                                        "max": 120,
                                        "increment": 6
                                    },
                                    "amountInPence": {
                                        "min": 750000,
                                        "max": 500000,
                                        "increment": 5000
                                    }
                                }
                            ]
                        },
                        {
                            "id": "HO",
                            "name": "Holiday",
                            "suggested": {
                                "termInMonths": [
                                    24,
                                    36,
                                    48,
                                    60
                                ],
                                "amountInPence": [
                                    200000,
                                    500000,
                                    100000,
                                    2500000
                                ]
                            },
                            "criteria": [
                                {
                                    "termInMonths": {
                                        "min": 24,
                                        "max": 60,
                                        "increment": 6
                                    },
                                    "amountInPence": {
                                        "min": 100000,
                                        "max": 500000,
                                        "increment": 5000
                                    }
                                }
                            ]
                        }
                    ]
                }
            },
            "CriteriaValue": {
                "type": "object",
                "properties": {
                    "min": {
                        "type": "integer",
                        "format": "int32"
                    },
                    "max": {
                        "type": "integer",
                        "format": "int32"
                    },
                    "increment": {
                        "type": "integer",
                        "format": "int32"
                    }
                },
                "required": [
                    "min",
                    "max",
                    "increment"
                ]
            },
            "CreateIllustrationPersonalLoanRequest": {
                "type": "object",
                "required": [
                    "termInMonths",
                    "amountInPence",
                    "purposeId"
                ],
                "properties": {
                    "termInMonths": {
                        "type": "integer"
                    },
                    "amountInPence": {
                        "type": "integer"
                    },
                    "purposeId": {
                        "type": "string",
                        "enum": [
                            "NV (New Vehicle)",
                            "UV (Used Vehicle)",
                            "HI (Home Improvements)",
                            "HG (Household Goods)",
                            "HO (Holiday)",
                            "DC (Debt Consolidation)",
                            "WE (Wedding)",
                            "OP (Other Acceptable Purposes)"
                        ]
                    },
                    "customerId": {
                        "type": "string"
                    }
                },
                "example": {
                    "termInMonths": 48,
                    "amountInPence": 3000000,
                    "purposeId": "HI",
                    "customerId": "ABC123FED"
                }
            },
            "CreateIllustrationPersonalLoanResponse": {
                "type": "object",
                "properties": {
                    "decision": {
                        "type": "string",
                        "enum": [
                            "ACCEPTED",
                            "DECLINED"
                        ]
                    },
                    "personalLoanIllustration": {
                        "type": "object",
                        "properties": {
                            "apr": {
                                "type": "integer",
                                "format": "int32",
                                "description": "Returned as basis points"
                            },
                            "interestRate": {
                                "type": "integer",
                                "format": "int32"
                            },
                            "totalRepaymentInPence": {
                                "type": "integer",
                                "format": "int32"
                            },
                            "totalInterestInPence": {
                                "type": "integer",
                                "format": "int32"
                            },
                            "repayment": {
                                "type": "object",
                                "properties": {
                                    "amountInPence": {
                                        "type": "integer",
                                        "format": "int32",
                                        "description": "Amount in pence (base unit)"
                                    },
                                    "interval": {
                                        "type": "string",
                                        "enum": [
                                            "MONTHLY",
                                            "QUARTERLY",
                                            "HALF_YEARLY",
                                            "YEARLY"
                                        ]
                                    }
                                },
                                "required": [
                                    "amountInPence",
                                    "interval"
                                ]
                            }
                        }
                    },
                    "reasons": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "id": {
                                    "type": "string"
                                },
                                "code": {
                                    "type": "string"
                                },
                                "text": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                },
                "required": [
                    "decision",
                    "reasons"
                ],
                "example": {
                    "decision": "ACCEPTED",
                    "personalLoanIllustration": {
                        "apr": 330,
                        "interestRate": 340,
                        "totalRepaymentInPence": 1034664,
                        "totalInterestInPence": 34664,
                        "repayment": {
                            "amountInPence": 43111,
                            "interval": "MONTHLY"
                        }
                    },
                    "reasons": []
                }
            },
            "ErrorResponse": {
                "type": "object",
                "properties": {
                    "Code": {
                        "type": "string"
                    },
                    "Message": {
                        "type": "string"
                    },
                    "Errors": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "ErrorCode": {
                                    "type": "string"
                                },
                                "Message": {
                                    "type": "string"
                                }
                            },
                            "required": [
                                "ErrorCode",
                                "Message"
                            ]
                        }
                    }
                },
                "required": [
                    "Code",
                    "Message",
                    "Errors"
                ]
            }
        }
    }
}